#:schema node_modules/wrangler/config-schema.json
name = "vatsal-main"
main = "dist/_worker.js"
compatibility_date = "2024-03-18"
compatibility_flags = [ "nodejs_compat" ]
[assets]
directory = "dist"

# If you use sessions, uncomment and add your KV ID
# [[kv_namespaces]]
# binding = "SESSION"
# id = "xxxxxxxxxxxx"
