import { type IconType } from 'react-icons'
import {
  SiLinux,
  SiUbuntu,
  SiDebian,
  SiDocker,
  SiKubernetes,
  SiAnsible,
  SiTerraform,
  SiGit,
  SiCloudflare,
  SiCilium,
  SiNginx,
  SiPython,
  SiCplusplus,
  SiRust,
  SiR,
  SiJulia,
  SiTensorflow,
  SiPytorch,
  SiScikitlearn,
  SiKeras,
  SiApachespark,
  SiPandas,
  SiNumpy,
  SiTableau,
  SiPlotly,
  SiWeightsandbiases,
  SiMlflow,
  SiRay,
  SiJupyter,
  SiGooglecolab,
  SiPycharm,
  SiGithubcopilot,
  SiOpenai,
  SiFastapi,
  SiApacheairflow,
  SiPrefect,
  SiPostgresql,
  SiRedis,
  SiTimescale,
  SiClickhouse,
  SiDuckdb,
  SiSnowflake,
  SiApachekafka,
  SiNotion,
  SiSlack,
  SiConfluence,
  SiJira,
} from 'react-icons/si'
import {
  Shield,
  Server,
  Network,
  Cloud,
  Terminal,
  Brain,
  MessageSquare,
  Database,
  TrendingUp,
  BarChart,
  Search,
  Settings,
  Wrench,
  LineChart,
  Target,
  Share2,
  Globe,
  RefreshCw,
  BarChart2,
  Calculator,
  Briefcase,
  ClipboardCheck,
  DollarSign,
  Activity,
  PieChart,
  Zap,
  Layers,
  Handshake,
  Cpu,
  Bot,
  Microscope,
  ClipboardList,
  Puzzle,
  Clock,
} from 'lucide-react'

// Icon mapping - clean and tailored for Quant Research & Trading Systems
export const iconMap: { [key: string]: IconType } = {
  // Systems & Infra
  'simple-icons:linux': SiLinux,
  'mdi:ubuntu': SiUbuntu,
  'simple-icons:debian': SiDebian,
  'mdi:docker': SiDocker,
  'mdi:kubernetes': SiKubernetes,
  'lucide:terminal': Terminal,
  'mdi:git': SiGit,
  'lucide:cloud': Cloud,
  'simple-icons:cloudflare': SiCloudflare,
  'lucide:server': Server,
  'simple-icons:cilium': SiCilium,
  'simple-icons:nginx': SiNginx,
  'lucide:network': Network,
  'lucide:cpu': Cpu,
  'lucide:zap': Zap,

  // Languages
  'simple-icons:python': SiPython,
  'simple-icons:cplusplus': SiCplusplus,
  'simple-icons:rust': SiRust,
  'simple-icons:r': SiR,
  'simple-icons:julia': SiJulia,

  // AI / ML / Quant Science
  'lucide:brain': Brain,
  'lucide:database': Database,
  'lucide:trending-up': TrendingUp,
  'lucide:bar-chart': BarChart,
  'lucide:search': Search,
  'lucide:settings': Settings,
  'lucide:wrench': Wrench,
  'lucide:chart-line': LineChart,
  'lucide:target': Target,
  'lucide:share-2': Share2,
  'lucide:globe': Globe,
  'simple-icons:tensorflow': SiTensorflow,
  'simple-icons:pytorch': SiPytorch,
  'simple-icons:scikitlearn': SiScikitlearn,
  'simple-icons:keras': SiKeras,
  'simple-icons:apachespark': SiApachespark,
  'simple-icons:pandas': SiPandas,
  'simple-icons:numpy': SiNumpy,
  'simple-icons:tableau': SiTableau,
  'simple-icons:plotly': SiPlotly,
  'simple-icons:weightsandbiases': SiWeightsandbiases,
  'simple-icons:mlflow': SiMlflow,
  'simple-icons:ray': SiRay,

  // Quant Research & Trading
  'lucide:line-chart': LineChart,
  'lucide:refresh-cw': RefreshCw,
  'lucide:bar-chart-2': BarChart2,
  'lucide:calculator': Calculator,
  'lucide:briefcase': Briefcase,
  'lucide:clipboard-check': ClipboardCheck,
  'lucide:dollar-sign': DollarSign,
  'lucide:activity': Activity,
  'lucide:pie-chart': PieChart,
  'lucide:layers': Layers,
  'lucide:handshake': Handshake,
  'lucide:shield': Shield,

  // Dev Tools & Platforms
  'simple-icons:jupyter': SiJupyter,
  'simple-icons:googlecolab': SiGooglecolab,
  'simple-icons:pycharm': SiPycharm,
  'simple-icons:githubcopilot': SiGithubcopilot,
  'simple-icons:openai': SiOpenai,
  'lucide:bot': Bot,
  'simple-icons:fastapi': SiFastapi,
  'simple-icons:apacheairflow': SiApacheairflow,
  'simple-icons:prefect': SiPrefect,
  'simple-icons:ansible': SiAnsible,
  'simple-icons:terraform': SiTerraform,

  // Financial Databases
  'simple-icons:postgresql': SiPostgresql,
  'simple-icons:redis': SiRedis,
  'simple-icons:timescale': SiTimescale,
  'simple-icons:clickhouse': SiClickhouse,
  'simple-icons:duckdb': SiDuckdb,
  'simple-icons:snowflake': SiSnowflake,
  'simple-icons:apachekafka': SiApachekafka,

  // Collaboration
  'simple-icons:notion': SiNotion,
  'simple-icons:slack': SiSlack,
  'simple-icons:confluence': SiConfluence,
  'simple-icons:jira': SiJira,

  // Soft & Research Skills
  'lucide:microscope': Microscope,
  'lucide:clipboard-list': ClipboardList,
  'lucide:puzzle': Puzzle,
  'lucide:clock': Clock,
}

export function getIcon(logo: string): IconType | null {
  return iconMap[logo] || null
}
