import { type IconType } from 'react-icons'
import {
  SiLinux,
  SiUbuntu,
  SiDebian,
  SiProxmox,
  SiDocker,
  SiKubernetes,
  SiCisco,
  SiPfsense,
  SiFortinet,
  SiPaloaltonetworks,
  SiAnsible,
  SiTerraform,
  SiPuppet,
  SiSaltproject,
  SiGit,
  SiFlux,
  SiRancher,
  SiOracle,
  SiCloudflare,
  SiCilium,
  SiPortainer,
  SiAsterisk,
  SiApache,
  SiNginx,
  SiMysql,
  SiWordpress,
  SiCpanel,
  SiPython,
  SiCplusplus,
  SiR,
  SiJulia,
  SiHtml5,
  SiCss3,
  SiTailwindcss,
  SiReact,
  SiNextdotjs,
  SiTensorflow,
  SiPytorch,
  SiScikitlearn,
  SiKeras,
  SiApachespark,
  SiOpencv,
  SiHuggingface,
  SiPandas,
  SiNumpy,
  SiPlotly,
  SiWeightsandbiases,
  SiMlflow,
  SiDvc,
  SiRay,
  SiJupyter,
  SiGooglecolab,
  SiPycharm,
  SiGithubcopilot,
  SiOpenai,
  SiFastapi,
  SiApacheairflow,
  SiPrefect,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiInfluxdb,
  SiTimescale,
  SiClickhouse,
  SiDuckdb,
  SiSnowflake,
  SiDatabricks,
  SiGooglebigquery,
  SiApachekafka,
  SiNotion,
  SiMailchimp,
  SiSlack,
  SiConfluence,
  SiJira,
  SiTrello,
  SiZoom,
  SiTableau,
  SiLangchain,
  SiStreamlit,
} from 'react-icons/si'
import {
  Shield,
  Server,
  Network,
  Cloud,
  HardDrive,
  Lock,
  Wifi,
  Terminal,
  CloudCog,
  Box,
  Brain,
  MessageSquare,
  Eye,
  MessageCircle,
  Database,
  TrendingUp,
  BarChart,
  Search,
  Settings,
  Wrench,
  LineChart,
  Target,
  Share2,
  Globe,
  RefreshCw,
  BarChart2,
  Calculator,
  Briefcase,
  ClipboardCheck,
  DollarSign,
  Activity,
  PieChart,
  Zap,
  Layers,
  Handshake,
  Cpu,
  Bot,
  Microscope,
  ClipboardList,
  Puzzle,
  Clock,
  Users,
} from 'lucide-react'

// Icon mapping - using direct imports for better tree-shaking
export const iconMap: { [key: string]: IconType } = {
  'simple-icons:linux': SiLinux,
  'mdi:ubuntu': SiUbuntu,
  'simple-icons:debian': SiDebian,
  'mdi:windows': Server,
  'simple-icons:proxmox': SiProxmox,
  'mdi:docker': SiDocker,
  'mdi:kubernetes': SiKubernetes,
  'lucide:box': Box,
  'simple-icons:cisco': SiCisco,
  'simple-icons:pfsense': SiPfsense,
  'simple-icons:fortinet': SiFortinet,
  'simple-icons:paloaltonetworks': SiPaloaltonetworks,
  'lucide:wifi': Wifi,
  'lucide:network': Network,
  'lucide:lock': Lock,
  'lucide:shield': Shield,
  'simple-icons:ansible': SiAnsible,
  'simple-icons:terraform': SiTerraform,
  'simple-icons:puppet': SiPuppet,
  'simple-icons:saltproject': SiSaltproject,
  'lucide:terminal': Terminal,
  'mdi:git': SiGit,
  'simple-icons:flux': SiFlux,
  'simple-icons:rancher': SiRancher,
  'lucide:cloud': Cloud,
  'simple-icons:oracle': SiOracle,
  'simple-icons:cloudflare': SiCloudflare,
  'lucide:server': Server,
  'lucide:cloud-cog': CloudCog,
  'simple-icons:cilium': SiCilium,
  'simple-icons:portainer': SiPortainer,
  'lucide:hard-drive': HardDrive,
  'simple-icons:asterisk': SiAsterisk,
  'simple-icons:apache': SiApache,
  'simple-icons:nginx': SiNginx,
  'simple-icons:mysql': SiMysql,
  'simple-icons:wordpress': SiWordpress,
  'simple-icons:cpanel': SiCpanel,
  'simple-icons:python': SiPython,
  'simple-icons:cplusplus': SiCplusplus,
  'simple-icons:r': SiR,
  'simple-icons:julia': SiJulia,
  'simple-icons:html5': SiHtml5,
  'simple-icons:css3': SiCss3,
  'simple-icons:tailwindcss': SiTailwindcss,
  'simple-icons:react': SiReact,
  'simple-icons:nextdotjs': SiNextdotjs,
  'lucide:brain': Brain,
  'lucide:message-square': MessageSquare,
  'lucide:eye': Eye,
  'lucide:message-circle': MessageCircle,
  'lucide:database': Database,
  'lucide:trending-up': TrendingUp,
  'lucide:bar-chart': BarChart,
  'lucide:search': Search,
  'lucide:settings': Settings,
  'lucide:wrench': Wrench,
  'lucide:chart-line': LineChart,
  'lucide:target': Target,
  'lucide:share-2': Share2,
  'lucide:globe': Globe,
  'simple-icons:tensorflow': SiTensorflow,
  'simple-icons:pytorch': SiPytorch,
  'simple-icons:scikitlearn': SiScikitlearn,
  'simple-icons:keras': SiKeras,
  'simple-icons:apachespark': SiApachespark,
  'simple-icons:opencv': SiOpencv,
  'simple-icons:huggingface': SiHuggingface,
  'simple-icons:pandas': SiPandas,
  'simple-icons:numpy': SiNumpy,
  'simple-icons:matplotlib': SiPython, // Simple icons doesn't have matplotlib, using python as fallback
  'simple-icons:tableau': SiTableau,
  'simple-icons:langchain': SiLangchain,
  'simple-icons:streamlit': SiStreamlit,
  'simple-icons:plotly': SiPlotly,
  'simple-icons:weightsandbiases': SiWeightsandbiases,
  'simple-icons:mlflow': SiMlflow,
  'simple-icons:dvc': SiDvc,
  'simple-icons:ray': SiRay,
  'lucide:line-chart': LineChart,
  'lucide:refresh-cw': RefreshCw,
  'lucide:bar-chart-2': BarChart2,
  'lucide:calculator': Calculator,
  'lucide:briefcase': Briefcase,
  'lucide:clipboard-check': ClipboardCheck,
  'lucide:dollar-sign': DollarSign,
  'lucide:activity': Activity,
  'lucide:pie-chart': PieChart,
  'lucide:bar-chart-3': BarChart,
  'lucide:zap': Zap,
  'lucide:layers': Layers,
  'lucide:handshake': Handshake,
  'lucide:cpu': Cpu,
  'simple-icons:jupyter': SiJupyter,
  'simple-icons:googlecolab': SiGooglecolab,
  'simple-icons:pycharm': SiPycharm,
  'simple-icons:githubcopilot': SiGithubcopilot,
  'simple-icons:openai': SiOpenai,
  'lucide:bot': Bot,
  'simple-icons:fastapi': SiFastapi,
  'simple-icons:apacheairflow': SiApacheairflow,
  'simple-icons:prefect': SiPrefect,
  'simple-icons:postgresql': SiPostgresql,
  'simple-icons:mongodb': SiMongodb,
  'simple-icons:redis': SiRedis,
  'simple-icons:influxdb': SiInfluxdb,
  'simple-icons:timescale': SiTimescale,
  'simple-icons:clickhouse': SiClickhouse,
  'simple-icons:duckdb': SiDuckdb,
  'simple-icons:snowflake': SiSnowflake,
  'simple-icons:databricks': SiDatabricks,
  'simple-icons:googlebigquery': SiGooglebigquery,
  'simple-icons:apachekafka': SiApachekafka,
  'simple-icons:notion': SiNotion,
  'simple-icons:mailchimp': SiMailchimp,
  'simple-icons:slack': SiSlack,
  'simple-icons:confluence': SiConfluence,
  'simple-icons:jira': SiJira,
  'simple-icons:trello': SiTrello,
  'simple-icons:zoom': SiZoom,
  'lucide:microscope': Microscope,
  'lucide:clipboard-list': ClipboardList,
  'lucide:puzzle': Puzzle,
  'lucide:clock': Clock,
  'lucide:users': Users,
}

export function getIcon(logo: string): IconType | null {
  return iconMap[logo] || null
}

